/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as extensions from "./extensions";
export type { extensions };
export type { INFTContractBase } from "./INFTContractBase";
export type { NFTContractBase } from "./NFTContractBase";
