/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as nftContractNoRoyaltiesSol from "./NFTContract_no_royalties.sol";
export type { nftContractNoRoyaltiesSol };
export type { Azuki } from "./Azuki";
export type { Multicall } from "./Multicall";
export type { NFTContract } from "./NFTContract";
